server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_profile_service
    username: postgres
    password: admin

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    topic:
      friend-requests: friend-request-events
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  redis:
    host: localhost
    port: 6379
